name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Open Server
        run: mvn --batch-mode --update-snapshots exec:java -PServer
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
