name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: BD
        run: mysql -u root -e "DROP SCHEMA IF EXISTS pscHotel;"
        run: mysql -u root -e "DROP USER IF EXISTS 'spq'@'localhost';"
        run: mysql -u root -e "CREATE SCHEMA pscHotel;"
        run: mysql -u root -e "CREATE USER IF NOT EXISTS 'spq'@'localhost' IDENTIFIED BY 'spq';"
        run: mysql -u root -e "GRANT ALL ON pscHotel.* TO 'spq'@'localhost';"
      - name: clean compile
        run: mvn clean compile
      - name: Create Schema
        run: mvn datanucleus:schema-create 
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
