language: java

jdk:
  - openjdk8

services: 
  - mysql
before_script:
- mysql -u root -e "DROP SCHEMA IF EXISTS pscHotel;"
- mysql -u root -e "DROP USER IF EXISTS 'spq'@'localhost';"
- mysql -u root -e "CREATE SCHEMA pscHotel;"
- mysql -u root -e "CREATE USER IF NOT EXISTS 'spq'@'localhost' IDENTIFIED BY 'spq';"
- mysql -u root -e "GRANT ALL ON pscHotel.* TO 'spq'@'localhost';"

script:
 - mvn clean compile
 - mvn datanucleus:schema-create 
 - mvn test
 
branches:
  only:
  - master
  
notifications:
  email:
    recipients:
      - kevin.arnaiz@opendeusto.es
      
    on_success: never
    on_failure: always
